### ISSUE TITLE
Improve website accessibility

### ISSUE THREAD

**Issue by narsaskpvt** [narsaskpvt/mcp-test-website-demo#4]
We need to improve the website's accessibility to make it more inclusive.

Tasks:
- [ ] Add ARIA labels to navigation
- [ ] Improve color contrast
- [ ] Add skip navigation link
- [ ] Ensure proper heading hierarchy
- [ ] Add alt text to any future images
- [ ] Add focus styles for keyboard navigation

Example improvements:
```html
<!-- Skip Navigation -->
<a href="#main-content" class="skip-nav">Skip to main content</a>

<!-- ARIA labels -->
<nav aria-label="Main navigation">
  <ul role="menubar">
    <li role="menuitem"><a href="#home">Home</a></li>
    <!-- ... other menu items ... -->
  </ul>
</nav>

<!-- Proper heading hierarchy -->
<main id="main-content">
  <!-- ... content ... -->
</main>
```

CSS improvements needed:
```css
.skip-nav {
  position: absolute;
  top: -40px;
  left: 0;
  padding: 8px;
  background: #000;
  color: #fff;
  z-index: 100;
}

.skip-nav:focus {
  top: 0;
}

/* Focus styles */
a:focus {
  outline: 2px solid #4A90E2;
  outline-offset: 2px;
}
```
